### PR TITLE
Solves the problem with hanging Home Assistand UI that was documented with issue #731

### PR DESCRIPTION
**Pull request by Zwer2k**
By replacing threading.Lock() with asyncio.Lock() and using the async methods of the pymodbus.client library, problem #731 is solved.
Tested with Sofar Solar HYD 10KTL-3ph inverter.
Unfortunately I don't have that much experience with Phython, so the solution may not be implemented very nicely.
Other plugins are also adapted, but not tested.

### CODE REVIEW

**Comment by wills106** [comment]
Thanks I'll take time to have a look at this.
I have tried a few times to adopt async to try and get around the blocking calls issue.

One thing I have quickly noticed is that this update deletes plugin_swatten.py

**Comment by Zwer2k** [comment]
That would make me very happy. With the changes, the HA-UI works much more smoothly for me and no longer hangs at all.
Many thanks for the great integration

**Comment by Zwer2k** [comment]
I use Waveshare Ethernet-RS485.
I can test with USB-RS485 this evening and check the code to see if I notice anything.

**Comment by Zwer2k** [comment]
I had to move the connect() methods to async_get_inverter_type because it didn't work with async_add_solax_modbus_sensor. 
Maybe there is still something wrong at this point

**Comment by Zwer2k** [comment]
And the lock() for close() is currently commented out because close() cannot do async

**Comment by wills106** [comment]
Seems to be working fin on my SolaX now with the built in Ethernet.
Is it possible to undelete plugin_swaten.py I can update it with the changes needed.

**Comment by wills106** [comment]
I have just updated and added https://github.com/wills106/homeassistant-solax-modbus/blob/main/custom_components/solax_modbus/plugin_swatten.py back in.
Could you confirm if it looks like I have made the changes correctly?

**Comment by wills106** [comment]
Have you been able to test writing to your Inverter with the new `async` calls?
I've been getting errors when trying to write. #768 
I'll have a look at the write code. See If I can spot anything.

**Comment by Zwer2k** [comment]
> I have just updated and added https://github.com/wills106/homeassistant-solax-modbus/blob/main/custom_components/solax_modbus/plugin_swatten.py back in. Could you confirm if it looks like I have made the changes correctly?

Looks correct to me

**Comment by wrfz** [comment]
The change is great. The various hangs that I've had in different places for months (e.g. when different lights were switched on or off) are now gone.

But I have now this error:
```
2024-02-23 08:27:59.659 WARNING (MainThread) [pymodbus.logging] Failed to connect
2024-02-23 08:27:59.786 WARNING (MainThread) [custom_components.solax_modbus.plugin_sofar] Sofar-15KTL: attempt to read serialnumber failed at 0x445
Traceback (most recent call last):
File "/config/custom_components/solax_modbus/plugin_sofar.py", line 63, in async_read_serialnr
inverter_data = await hub.async_read_holding_registers(unit=hub._modbus_addr, address=address, count=7)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/solax_modbus/__init__.py", line 370, in async_read_holding_registers
return await self._client.read_holding_registers(address, count, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/pymodbus/client/base.py", line 199, in async_execute
resp = await asyncio.wait_for(
^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/asyncio/tasks.py", line 520, in wait_for
return await fut
^^^^^^^^^
pymodbus.exceptions.ConnectionException: Modbus Error: [Connection] Connection lost during request
2024-02-23 08:27:59.796 WARNING (MainThread) [custom_components.solax_modbus.plugin_sofar] Sofar-15KTL: reading serial number from address 0x445 failed; other address may succeed
2024-02-23 08:27:59.796 ERROR (MainThread) [custom_components.solax_modbus.plugin_sofar] Sofar-15KTL: cannot find serial number, even not for other Inverter
2024-02-23 08:27:59.796 ERROR (MainThread) [custom_components.solax_modbus.plugin_sofar] unrecognized Sofar-15KTL inverter type - serial number : unknown
```

The error only occurs once when I restart HA. 
When the system is running, it appears to be stable. All values come reliably from the Solax integration.

The error has reproducibly occurred 3 times after 3 restarts.

I'm on 2024.02.6b4 and have a Sofar HYD 15KTL-3ph.

**Comment by wrfz** [comment]
The error probably occurs because the Modbus connection cannot be established.
pymodbus throws the error: `[pymodbus.logging] Failed to connect`.
A strange thing is that `await self._client.connect()` returns a `True` and thus says that the connection has been established.
Querying the getter `self._client.connected` also returns a `True` despite the previous error message.
Seems to be an issue in `pymodbus.AsyncModbusTcpClient`.

**Comment by wrfz** [comment]
Today I installed Solax integration on another system (devcontainer), which is more powerful in terms of hardware.
Communication with the inverter works perfectly here. 
My Raspi must have some kind of timing problem.

**Comment by wrfz** [comment]
If I add a sleep at the beginning in `__init__.py` -> `async_setup_entry(...)`, then the error no longer occurs and HA starts reproducibly without errors:
```
async def async_setup_entry(hass: HomeAssistant, entry: ConfigEntry):
    """Set up a SolaX mobus."""

    await asyncio.sleep(5)

    _LOGGER.debug(f"setup entries - data: {entry.data}, options: {entry.options}")
    config = entry.options
    ...
```

**Comment by wills106** [comment]
I'll add this in and release a Beta. It looks like async has quite a speed increase according to https://pymodbus.readthedocs.io/en/dev/source/examples.html#client-performance-sync-vs-async perhaps it's starting up a bit too quick for some Inverters?

Hopefully this change will help with #770 #771 #773

**Comment by Zwer2k** [comment]
We may have found a better approach than sleep(5) with @wrfz . We will create a merge request later

**Comment by wills106** [comment]
Thanks for looking into this as it's a bit difficult for me to fix an issue I can't replicate.

**Comment by wrfz** [comment]
@wills106 This should solve connection problems: [https://github.com/wills106/homeassistant-solax-modbus/pull/778](https://github.com/wills106/homeassistant-solax-modbus/pull/778)

**Comment by cschlipf** [comment]
@Zwer2k - have you tested your changes also with writing registers? SInce this change I am running into several problems when trying to write registers. e.g. when trying to update Battery Charge/Discharge Power:

```
2024-03-16 19:26:16.420 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [3624608936] Modbus Error: [Input/Output] ERROR: No response received after 3 retries
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 240, in handle_call_service
response = await hass.services.async_call(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/core.py", line 2279, in async_call
response_data = await coro
^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/core.py", line 2316, in _execute_service
return await target(service_call)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 892, in entity_service_call
single_response = await _handle_entity_call(
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 962, in _handle_entity_call
result = await task
^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/select/__init__.py", line 195, in async_handle_select_option
await self.async_select_option(option)
File "/config/custom_components/solax_modbus/select.py", line 106, in async_select_option
await self._hub.async_write_registers_single(unit=self._modbus_addr, address=self._register, payload=payload)
File "/config/custom_components/solax_modbus/__init__.py", line 428, in async_write_registers_single
return await self._client.write_registers(address, payload[0], **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/pymodbus/client/base.py", line 180, in async_execute
raise ModbusIOException(
pymodbus.exceptions.ModbusIOException: Modbus Error: [Input/Output] ERROR: No response received after 3 retries
2024-03-16 19:26:16.443 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [3624608936] Modbus Error: [Connection] Not connected[AsyncModbusTcpClient 192.168.158.13:8899]
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 240, in handle_call_service
response = await hass.services.async_call(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/core.py", line 2279, in async_call
response_data = await coro
^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/core.py", line 2316, in _execute_service
return await target(service_call)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 892, in entity_service_call
single_response = await _handle_entity_call(
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 962, in _handle_entity_call
result = await task
^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/button/__init__.py", line 139, in _async_press_action
await self.async_press()
File "/config/custom_components/solax_modbus/button.py", line 91, in async_press
await self._hub.async_write_registers_multi(
File "/config/custom_components/solax_modbus/__init__.py", line 470, in async_write_registers_multi
return await self._client.write_registers(address, payload, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/pymodbus/client/mixin.py", line 389, in write_registers
return self.execute(
^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/pymodbus/client/base.py", line 152, in execute
raise ConnectionException(f"Not connected[{self!s}]")
pymodbus.exceptions.ConnectionException: Modbus Error: [Connection] Not connected[AsyncModbusTcpClient 192.168.158.13:8899]
2024-03-16 19:26:16.872 ERROR (MainThread) [pymodbus.logging] General exception: unpack requires a buffer of 4 bytes
2024-03-16 19:26:16.873 ERROR (MainThread) [homeassistant] Error doing job: Fatal error: protocol.data_received() call failed.
Traceback (most recent call last):
File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 1013, in _read_ready__data_received
self._protocol.data_received(data)
File "/usr/local/lib/python3.12/site-packages/pymodbus/transport/transport.py", line 303, in data_received
self.datagram_received(data, None)
File "/usr/local/lib/python3.12/site-packages/pymodbus/transport/transport.py", line 337, in datagram_received
cut = self.callback_data(self.recv_buffer, addr=addr)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/pymodbus/client/base.py", line 201, in callback_data
self.framer.processIncomingPacket(data, self._handle_response, slave=0)
File "/usr/local/lib/python3.12/site-packages/pymodbus/framer/base.py", line 139, in processIncomingPacket
self.frameProcessIncomingPacket(single, callback, slave, **kwargs)
File "/usr/local/lib/python3.12/site-packages/pymodbus/framer/socket_framer.py", line 106, in frameProcessIncomingPacket
raise ModbusIOException("Unable to decode request")
pymodbus.exceptions.ModbusIOException: Modbus Error: [Input/Output] Unable to decode request
2024-03-16 19:26:17.277 ERROR (MainThread) [pymodbus.logging] General exception: unpack requires a buffer of 4 bytes
2024-03-16 19:26:17.277 ERROR (MainThread) [homeassistant] Error doing job: Fatal error: protocol.data_received() call failed.
Traceback (most recent call last):
File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 1013, in _read_ready__data_received
self._protocol.data_received(data)
File "/usr/local/lib/python3.12/site-packages/pymodbus/transport/transport.py", line 303, in data_received
self.datagram_received(data, None)
File "/usr/local/lib/python3.12/site-packages/pymodbus/transport/transport.py", line 337, in datagram_received
cut = self.callback_data(self.recv_buffer, addr=addr)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/pymodbus/client/base.py", line 201, in callback_data
self.framer.processIncomingPacket(data, self._handle_response, slave=0)
File "/usr/local/lib/python3.12/site-packages/pymodbus/framer/base.py", line 139, in processIncomingPacket
self.frameProcessIncomingPacket(single, callback, slave, **kwargs)
File "/usr/local/lib/python3.12/site-packages/pymodbus/framer/socket_framer.py", line 106, in frameProcessIncomingPacket
raise ModbusIOException("Unable to decode request")
pymodbus.exceptions.ModbusIOException: Modbus Error: [Input/Output] Unable to decode request
2024-03-16 19:26:17.863 ERROR (MainThread) [pymodbus.logging] General exception: unpack requires a buffer of 4 bytes
2024-03-16 19:26:17.864 ERROR (MainThread) [homeassistant] Error doing job: Fatal error: protocol.data_received() call failed.
Traceback (most recent call last):
File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 1013, in _read_ready__data_received
self._protocol.data_received(data)
File "/usr/local/lib/python3.12/site-packages/pymodbus/transport/transport.py", line 303, in data_received
self.datagram_received(data, None)
File "/usr/local/lib/python3.12/site-packages/pymodbus/transport/transport.py", line 337, in datagram_received
cut = self.callback_data(self.recv_buffer, addr=addr)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/pymodbus/client/base.py", line 201, in callback_data
self.framer.processIncomingPacket(data, self._handle_response, slave=0)
File "/usr/local/lib/python3.12/site-packages/pymodbus/framer/base.py", line 139, in processIncomingPacket
self.frameProcessIncomingPacket(single, callback, slave, **kwargs)
File "/usr/local/lib/python3.12/site-packages/pymodbus/framer/socket_framer.py", line 106, in frameProcessIncomingPacket
raise ModbusIOException("Unable to decode request")
pymodbus.exceptions.ModbusIOException: Modbus Error: [Input/Output] Unable to decode request
```


cc: @wills106

**Comment by Zwer2k** [comment]
Hello Carsten,

yes, I also tested my changes with write registers and couldn't find any problems, everything worked as desired. However, I am not currently using any automations that use write operations. 
The problem is that when using non-async, the HA user interface with the integration was very difficult to use, there were constant hangs. It may be necessary to check whether reconnect is being performed correctly.

What hardware are you using for HA and what Modbus hardware?

**Comment by cschlipf** [comment]
Hardware is a Raspberry PI 4 and I am connecting via the LSE-3

**Comment by cschlipf** [comment]
@Zwer2k - can you please test whether you are still able to change "Passive: Maximum Power" and "Passive: Minimum Power"? Last time this worked for me was before your change.

**Comment by Zwer2k** [comment]
Actually looks good

image

2024-03-17 18:10:10.684 INFO (MainThread) [custom_components.solax_modbus.select] writing Sofar select register 4368 value 3
2024-03-17 18:10:21.982 INFO (MainThread) [custom_components.solax_modbus.number] *** local data written passive_mode_battery_power_max: 200
2024-03-17 18:10:26.812 INFO (MainThread) [custom_components.solax_modbus.number] *** local data written passive_mode_battery_power_min: 100
2024-03-17 18:10:31.081 INFO (MainThread) [custom_components.solax_modbus.number] *** local data written passive_mode_battery_power_max: 500

**Comment by cschlipf** [comment]
Are you also using an LSE-3 or have you connected your inverter differently?

**Comment by Zwer2k** [comment]
I use Waveshare rs485 to ETH. My HA runs as a VM under Proxmox.

**Comment by cschlipf** [comment]
Strange... I am even not seeing the message "writing Sofar select register 4368 value 3"

**Comment by Zwer2k** [comment]
The test was with version 2023.3.3, so it definitely works. 

However, I got an error with my Huawei inverter integration with this version. Version 2023.3.3 updated the pymodbus library to version 3.6.6, which led to problems.

**Comment by cschlipf** [comment]
Hm, could it be that the LSE-3 is the problem? Maybe the Waveshare adapter takes care of timing issues, while the LSE-3 just directly talks to the inverter without any caching or verification?

**Comment by Zwer2k** [comment]
I'll try my test installation of HA on Raspberry PI 3, maybe the problem occurs there. At the beginning, after the async implementation, there were timing problems with Raspberry PI.
Do you have an HA development environment running? Does the problem also occur there?

**Comment by wills106** [comment]
A waveshare may or maynot help.
Seems like some people with SolaX and Waveshare's are getting issues now.

I thought bumping pyModbus to v3.6.6 would help https://github.com/wills106/homeassistant-solax-modbus/issues/807#issuecomment-2002046726

But I'm not sure if v3.6.6 is now causing this last error https://github.com/wills106/homeassistant-solax-modbus/issues/771#issuecomment-2002559987 and I need to do something with `'intern'`

The strange thing is that I can't replicate a single issue with my setup. so trying to fix an issue a bit blind really.

**Comment by Zwer2k** [comment]
With Raspberry Pi 3 it also works for me without any problems

**Comment by Zwer2k** [comment]
@cschlipf 
I have made small adjustments. You can have a look to see if it helps.
https://github.com/Zwer2k/homeassistant-solax-modbus/commit/68b4ab29bb3ea44730775a1834e94e7c48b80a31

**Comment by cschlipf** [comment]
@Zwer2k - sorry, I did not had the time to check this earlier. Just tested your change with the latest version. Unfortunately I don't see any improvement. Trying to change the change the Energy Storage Mode:

```
2024-03-23 17:42:45.742 ERROR (MainThread) [pymodbus.logging] General exception: unpack requires a buffer of 4 bytes
2024-03-23 17:42:45.742 ERROR (MainThread) [homeassistant] Error doing job: Fatal error: protocol.data_received() call failed.
Traceback (most recent call last):
File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 1017, in _read_ready__data_received
self._protocol.data_received(data)
File "/usr/local/lib/python3.12/site-packages/pymodbus/transport/transport.py", line 303, in data_received
self.datagram_received(data, None)
File "/usr/local/lib/python3.12/site-packages/pymodbus/transport/transport.py", line 337, in datagram_received
cut = self.callback_data(self.recv_buffer, addr=addr)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/pymodbus/client/base.py", line 201, in callback_data
self.framer.processIncomingPacket(data, self._handle_response, slave=0)
File "/usr/local/lib/python3.12/site-packages/pymodbus/framer/base.py", line 139, in processIncomingPacket
self.frameProcessIncomingPacket(single, callback, slave, **kwargs)
File "/usr/local/lib/python3.12/site-packages/pymodbus/framer/socket_framer.py", line 106, in frameProcessIncomingPacket
raise ModbusIOException("Unable to decode request")
pymodbus.exceptions.ModbusIOException: Modbus Error: [Input/Output] Unable to decode request
```

**Pull request merged**
