### PR TITLE
Solis HMI Firmware FB00

### PR DESCRIPTION
**Pull request by fboundy**
Add support for Solis HMI firmware which:

- Simplifies the Energy Code Switch options 
- Has 6 charge and discharge slots rather than 3
- Has separate Current, Target SOC and Voltage for each Charge/Discharge slot

Note that on the inverter and in the SolisCloud API interface each slot also has an On/Off switch. I have not found a ModBus register for this so this will need to be set "ON" once on the inverter or through SolisCloud. It is also not clear what the Voltage target on each slot does.

### CODE REVIEW

**Comment by ajan1** [comment]
I have charge/discharge slot on/off switches in address 43707. Bits 0-5 charge 1-6 and bits 6-11 for discharge 1-6

I tried this pull. I didn't get how to enable/disable my time slots?

**Comment by fboundy** [comment]
I hadn’t managed to find those registers. I had to enable manually on the inverter. I’ll update and push a commit.

**Comment by fboundy** [comment]
No updated to add switches. This is quite a big PR as the SWITCHES platform wasn't previously used. I have added SWITCH_TYPES to the solis_fb00 plugin and empty lists to all the other plugins.

**Comment by wills106** [comment]
Need to relook into https://github.com/wills106/homeassistant-solax-modbus/issues/948#issuecomment-2217068383 to prevent all of these huge file diff's due to people having different formatting settings. It's making it impossible to know what's actually changed. Same with #1173 

@litinoveweedle @fboundy @PatrikTrestik any idea on the best approach / guide on how to set something up?
Last time I looked at VS Code plugin "Black Formatter" it made a right mess locally.

**Comment by fboundy** [comment]
I use Black in VS Code with --linelength=119

**Comment by fboundy** [comment]
On a separate note, I'm note sure whether it is best to keep this as a separate plugin or to try to merge it with `plugin_solis.py`. Register 33002 gives the relevant firmware version. If it is >= `0x4B` (75) then this new plugin should be used, otherwise the old one is correct. Just not quite sure how to implement this switch.

**Comment by fboundy** [comment]
> Need to relook into [#948 (comment)](https://github.com/wills106/homeassistant-solax-modbus/issues/948#issuecomment-2217068383) to prevent all of these huge file diff's due to people having different formatting settings. It's making it impossible to know what's actually changed. Same with #1173
> 
> @litinoveweedle @fboundy @PatrikTrestik any idea on the best approach / guide on how to set something up? Last time I looked at VS Code plugin "Black Formatter" it made a right mess locally.

ChatGPT says it's easy. I will have a try on one of my repos.

To deploy a GitHub CI workflow that runs the Black formatter on all commits, you can use GitHub Actions. Here's how to set it up:
Steps:

Create a .github/workflows directory in your repository if it doesn’t already exist.

Add a new YAML file for the workflow:
  Name it something like black-check.yml.

 Write the workflow:
   Below is an example workflow that uses Black to check Python files in your repository:

```
name: Black Formatter Check

on:
  push:
    branches:
      - main  # Specify the branches you want to check (e.g., main)
  pull_request:
    branches:
      - main  # Run checks for pull requests targeting main

jobs:
  black:
    name: Run Black Formatter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Black
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: Run Black Formatter
        run: black --check --diff .


```

**Comment by wills106** [comment]
I was thinking of adding GEN to older Firmware's and then adding in GEN2 for the newer.
https://github.com/wills106/homeassistant-solax-modbus/issues/1142#issuecomment-2506606021
Then have the relevant tags where they spilt. The GEN, GEN2, GEN3 etc used used quite a bit on SolaX as they share base registers and then split. But it's defined by the serial and not an extra Register ie 33002

I have just been too busy over the past few weeks to look at the various PR's on here / do any development.

**Comment by litinoveweedle** [comment]
Hello,

I am using for my project automatic formatters hooked to the CI (GitHub actions). It works as supposed -  runs on PR merge/push so code is always reformatted before merging - therefore you avoid this commits mess. I can try to help, although I am not an expert and my actions are mostly copy paste of existing examples. :-)

**Comment by wills106** [comment]
I have added in pyproject.toml with black and line-length 119
Is it possible to force VS Code to have black as a dependency in the pyproject.toml file? I'm quite new to this.

Also added in workflow for black as well with the same line-length

**Comment by fboundy** [comment]
I’ve got it set up now on my pvopt repo if you have a look in .github/workflows/black.yaml

**Pull request merged**
