### PR TITLE
Add shadow fix option to Solax

### PR DESCRIPTION
**Pull request by cewbdex**

### CODE REVIEW

**Comment by wills106** [comment]
I think the name and key should match with:

https://github.com/wills106/homeassistant-solax-modbus/blob/317455e04d8d17211869e1437ebc958de5531ea0/custom_components/solax_modbus/plugin_solax.py#L2238-L2248

So the values update when HA restarts. Although it looks like key to 0x104 should be updated to match the working of the name.

**Comment by cewbdex** [comment]
Right, I did not know it works like this, thanks.

**Comment by wills106** [comment]
Even though the sensor is disabled (register = 0x9C,) HA still reads that to populate the select on start up of HA, or if you manually change something on the Inverter itself. So the name / key needs to match. I'm not 100% sure which is the critical one that needs to match.

**Comment by cewbdex** [comment]
image
image

**Comment by wills106** [comment]
Oops got the read and the write register back to front in my reply.

But in the Integration the names need to match.

**Pull request merged**
