### PR TITLE
Growatt: Fix firmware control version format

### PR DESCRIPTION
**Pull request by TonyMathiesen**
This corrects the format to display the firmware control version: 
image

### CODE REVIEW

**Comment by TonyMathiesen** [comment]
Added a fix for serial number for GEN4, as register 23 is blank, so uses 3001 instead.

**Comment by wills106** [comment]
Have I merged these out of order as it's showing a conflict. Or is this PR missing parts of the PR for adding in the run modes?

**Comment by wills106** [comment]
Could do please. But I think it's all ok

**Comment by TonyMathiesen** [comment]
Everything seems ok 👍

**Comment by wills106** [comment]
Thanks, just released 2024.10.4 with all of the changes.

**Comment by TonyMathiesen** [comment]
Just updated. Thank you very much.

**Pull request merged**
