### PR TITLE
Refactor README.md III

### PR DESCRIPTION
**Pull request by cewbdex**
In my subjective view it looks better, but it's up to you to decide.

### CODE REVIEW

**Comment by wills106** [comment]
I think the PocketLAN / PocketWiFi info should stay near the top. The FAQ isn't exactly read very often.

**Comment by cewbdex** [comment]
I was thinking that it would be better to have something like github.io pages, now something is in readme and something in wiki and it's kinda confusing

**Comment by wills106** [comment]
github.io isn't something I have looked into.
But if it allows for other people to submit PR's for doc changes then it would be good. That's the main problem with the wiki there is only two of us that can update it and neither of us own non SolaX Inverters.
So there is limited documentation on non SolaX equipment.

**Comment by cewbdex** [comment]
Wiki could be moved to readthecods, [see here my test repo](https://rtdtestingelfs.readthedocs.io/en/latest/index.html)

**Comment by wills106** [comment]
I got as far as https://github.com/wills106/homeassistant-solax-modbus/tree/main/docs
Which can be found https://wills106.github.io/homeassistant-solax-modbus/

But at the time, I ran out of time to actually populate anything.
I haven't dealt with github.io or readthedocs.io before, which you do think offers an easier way for others to contribute?

**Comment by cewbdex** [comment]
I believe readthedocs is better, because is has a search functionality, which can make things easier. GitHub pages might be easier for contributors to contribute, as it uses markdown instead of restructuredtext, but the syntax is really simple too. Both have sources hosted on GitHub. I could try to move our existing wiki if you wish and then transfer ownership of the repo to you, we can have a new GitHub organisation to keep things organized.

**Comment by cewbdex** [comment]
Wiki is there: https://testmdp2.readthedocs.io/en/latest/intro.html

**Comment by cewbdex** [comment]
I am closing this, please review https://testmdp2.readthedocs.io/en/latest/ entire wiki is there, only some fixes needed, if you like it, we can move it to a new address and repo. Only install tutorial is missing there.

**Comment by wills106** [comment]
Noticed you have a repository of Firmwares for the Various models.

Have you come across anymore Changelogs for the X1 Hybrid Gen3 other than the changelogs in the Excel sheets?

**Comment by wills106** [comment]
Is the Syntax used on that readthedocs example compatible with GitHub / github.io or does it need conversion?

I think short term it might be best to put it in https://github.com/wills106/homeassistant-solax-modbus/tree/main/docs
Then we can at least get some contributions from owners of other Inverters. The biggest issue with the current Wiki is that people can't contribute. So the likes of Solis, Growatt etc have zero documentation.

I need to have a think on longer term branding of the Integration as it isn't SolaX exclusive anymore so a bit missleading.

**Comment by cewbdex** [comment]
I have done some investigation and I found readthedocs supports markdown, so it's almost 1:1, with some addition, I think it would be better to use RTD rather than GH pages, question is, do you want it to be hosted in this or separate repo? This is the code, you can see it's very simple, ignore repo name: <https://github.com/cewbdex/example-jupyter-book>

**Comment by wills106** [comment]
I think for the time being it's best staying in this repo. At least people can contribute to it for now.
Giving people the ability to easily submit doc updates is more important, as it will improve peoples experience with the Integration.

Like I say longer term I will look into a new Integration name and how to host things better. The Integration name needs to be more universal.

**Comment by cewbdex** [comment]
I missed your first comment. The repository is not mine, it was told to me that SolaX owns it, but I can't guarantee it, but multiple people tested it with multiple inverters and no problems so far.

**Comment by wills106** [comment]
No worries, I'll reach out to SolaX and see if there is any documentation on the changes.
I'm curious to know what's been changed in the various releases.

**Comment by cewbdex** [comment]
Maybe we could host somewhere a repo with all modbus documents we have, so it's easier to collaborate.

**Pull request closed without merging**
