### PR TITLE
made paths to plugins calculated instead of fixed

### PR DESCRIPTION
**Pull request by gelse**

### CODE REVIEW

**Comment by gelse** [comment]
bugfix for https://github.com/wills106/homeassistant-solax-modbus/issues/269

**Comment by infradom** [comment]
I believe we need to more, and avoid that the persistent config_entry variables contain paths.
I am trying a version that probably doesnt need paths .., but if that fails, your proposal could certainly be part of the solution

**Comment by infradom** [comment]
This has been implemented in a PR that also modifies the config_flow entries to  avoid paths in the entry
Thanks !

**Comment by wills106** [comment]
I'll close down as #272 resoles the same issue.

**Pull request closed without merging**
