### PR TITLE
Add SolaX bug form

### PR DESCRIPTION
**Pull request by cewbdex**
Forms provide richer experience over templates. They are easier to fill by users, can provide them more information and will force them to fill required information. Tags need to be created in order to be applied. My vision is to have per brand issue form, so it can be tailored exactly, but that's just my point of view and I could provide a generic one instead.

### CODE REVIEW

**Comment by wills106** [comment]
I think at the moment the form can stay generic. The only thing that would need changing is:

`label: First 6 digits of Serial`

`label: First 6 digits of Serial (Growatt Firmware Version)`

and perhaps make the `label: Inverter firmware versions` as I don't have any relevant information on other Brands.

Or another option is to keep solax.yml and have a second generic.yml that's a bit more looser for other Brands?

I think it's good though that you can set mandatory and optional Fields. I didn't realise this was possible.

**Comment by cewbdex** [comment]
I guess one for Solax and one generic for others would be fine. If I understand you correctly, the serial number is only relevant for Growatt? Or what do you mean by the suggested change? Mandatory and optional fields are only possible in forms, not templates (the current new issue approach). Here is how it will look like: https://github.com/cewbdex/homeassistant-solax-modbus/issues/new?assignees=&labels=bug%2Ctriage%2CSolax&projects=&template=solax.yml&title=%5BBug%5D%3A+

**Comment by wills106** [comment]
SolaX, Solis and Sofar use Serial Number to identify.
Growatt uses the Firmware version

> Mandatory and optional fields are only possible in forms

I was referring to your new form sorry, I loaded it up to look and it looks good.

**Comment by wills106** [comment]
Yea just done a bit of housekeeping.

**Pull request merged**
