### PR TITLE
Match externalgen entities

### PR DESCRIPTION
**Pull request by cewbdex**
I don't have any status for this entity and I found there is no matching sensor entity:
obrazek
Looked in the sheet and this looks like a match, please have a look and correct me if i am wrong.

### CODE REVIEW

**Comment by cewbdex** [comment]
There is also:
obrazek
I don't have a state for - the sensor entity has DCB allowedtype, but the number does not.

**Comment by wills106** [comment]
I was trying to move all of this Generator stuff to start with the same naming convention.

I intended for them all to start Generator xyz

It's probably the number & select that need's updating and the `config_maxexport_entity` updating.
I probably need to review the DCB tags as well so it's harmonised.

**Comment by cewbdex** [comment]
Do you think my changes will solve the problem correctly? I could look into the naming convention, update and send for review. Sadly that will probably break the API, but I guess this feature has no to a few users, so the change will have more positive than negative effect.

**Comment by cewbdex** [comment]
I don't have any Modbus document regarding external generator, so I can't check it, but the entities I matched were in my document. Now probably ready for review and merge.

**Comment by cewbdex** [comment]
I also believe that `generator_control` and `generator_max_charge` should have the `DCB` tag, so they are not normally exposed, as I don't believe they have any function without DCB. I can include it in my changes if you wish.

**Comment by wills106** [comment]
> I also believe that `generator_control` and `generator_max_charge` should have the `DCB` tag

Yes I agree

**Comment by cewbdex** [comment]
Done, ready for review.

**Pull request merged**
