### PR TITLE
Improve support for Growatt SPH 4kW - 10kW 3P TL UP

### PR DESCRIPTION
**Pull request by choenig**
Hi, 

this pull request adds more registers and improves others. This is a list of changes (in no particular order):

* Fix a typo in "Deutsch[e]"
* improve and extend holding-registers
    * explicitly rename 'Grid First', 'Battery First' and 'Load First'
    * BREAKING: rename entity-keys and -names
    * add "Battery First" intervals 4-6
    * add "Grid First" intervals 4-6
* add "AC Power to User *" sensors
* fix scaling of "EPS Loading" value
* add undocumented holding register 608 for load_first_battery_minimum_soc
* rename "Enable" options to "Enabled" to be in  line with the selects
* Add select for "Priority"

This PR changes entity-names for configuration for 'Grid First', 'Battery First' and 'Load First' and their various time intervals. Each set of configuration is named like
* grid_first_time_N
* grid_first_time_N_begin
* grid_first_time_N_end

I'm sure this also enhances other Growatt inverters, but I can only test with my `SPH 10kW 3P TL UP` :)

Happy review ;)

### CODE REVIEW

**Comment by hgnirke** [comment]
name = "Grid First Discharge Rate",
        key = "grid_first_discharge_rate",
        register = 1070,
        fmt = "i",
        native_min_value = 10, # docs say '0' here

My SPH3600 Single phase works 5% and up. 
Changed it to a lower value for better steering/control @ night with lower rates. With min 10% means for me @least 360w battery discharge wich is not always needed. Guess 0 in standard in code might help for easier integration.

**Comment by wills106** [comment]
@hgnirke Would it make sense to change "Grid First Battery Minimum SOC" as well to `native_min_value = 0`?

Also are you getting the issues mentioned in https://github.com/wills106/homeassistant-solax-modbus/issues/710#issuecomment-2408455180

**Comment by hgnirke** [comment]
Yes ... it is setable to zero via Webconfig on server.growatt.com.
So you can decide yourself if you want to drain your battery down to Zero or not or stop on this setable dedicated value like 3% or so. Guess I would put it on 3 because I see sometimes battery load jumps of 3% wich I guess come from loadbalancing under the batteries themselves. I my setting I have 3x50V 5KWh Batteries. And if they still have the chance to balance none of them yould make a emergency switch off... Where you have to turn on manually again if sun raises... But it depends on the setting and the batteries BMS and so on and so on. Its on solarmasters responsibility what to set. If he want zero he should be able to.

**Comment by wills106** [comment]
I have released [2024.10.1](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2024.10.1) with the changes.

**Comment by hgnirke** [comment]
image
This is ony "AC something" Value I have ... its mostly Zero and raises max to 100 but i don't know the circumstances when to change...

**Pull request merged**
