### PR TITLE
Add compatibility for Modbus RTU over TCP / Ascii over TCP

### PR DESCRIPTION
**Pull request by mludolph**
This change introduces the possibility to connect to RS485 adaptors that do not translate Modbus RTU to Modbus TCP but instead to Modbus RTU over TCP, such as the USR-TCP232-304 mentioned in the wiki. This was necessary to make the adapter work.

### CODE REVIEW

**Comment by wills106** [comment]
Thanks, I was expecting USR-TCP232-304 to only provide a virtual com port when I briefly looked at it. Unless that's Windows only?
Have you come across any adaptors using the ModbusAsciiFramer ?

**Comment by wills106** [comment]
Do you have access to any other RS485 adaptors?
I'm just wondering how selecting ModbusRTUFramer on a Waveshare for example would behave.
I only have an Ethernet connection on my Inverter, so I have no need for an adaptor and nothing to connect one to.

I'll need to be clear with the documentation in the Wiki so users don't select the wrong configuration now there is 3 TCP options.

**Comment by mludolph** [comment]
I did get the virtual COM port to work under windows but wasnt able to do so for ubuntu (tried using socat and mounting it into the docker container did not work). 

I do not have access to other adaptors nor have I seen one using ASCII over TCP but I figured since the application that I initially used for testing (Modbus Poll) provided these options, I might aswell include that option in case someone comes across such a device.

I do believe however that using Modbus RTU over TCP would not work e.g. using a Waveshare device since these seem to provide real Modbus TCP although I cannot test this.

Let me know in case there's anythihg I should change to make it less confusing for other users.

**Comment by alienatedsec** [comment]
> I do believe however that using Modbus RTU over TCP would not work 

Modbus RTU over TCP is the SolarMan v5 format that is used with Solis DLS-W (now obsolete) data loggers. There is great documentation about it, and initially I was trying this method with SolaX integration.

**Comment by jmccrohan** [comment]
> > I do believe however that using Modbus RTU over TCP would not work
> 
> Modbus RTU over TCP is the SolarMan v5 format that is used with Solis DLS-W (now obsolete) data loggers. There is great documentation about it, and initially, I was trying this method with SolaX integration #264
> 
> `[EDIT]` More about SolarMan protocol FYI - https://pysolarmanv5.readthedocs.io/en/latest/solarmanv5_protocol.html

Solarman loggers don't use Modbus RTU over TCP. The Solarman V5 protocol is different. However, I've just tidied up and published something I wrote a while back to encapsulate Modbus RTU over TCP frames in Solarman V5 frames. If it is of use, I'll look to package it up as a Home Assistant Addon.

https://github.com/jmccrohan/pysolarmanv5/blob/main/examples/solarman_proxy.py

**Pull request merged**
